### ISSUE TITLE
Module not listed in Advanced

### ISSUE THREAD

**Issue by thelton** [bitExpert/magento2-force-login#10]
Tried to install on Magento 2.0.7, files loaded fine but the module isn't listing in Stores > Configuration > Advanced.

**Comment by websharp** [comment]
Hello @thelton I am sorry, but I can not reproduce your issue, see image below. Can you double-check again, please?

![magento2_advanced](https://cloud.githubusercontent.com/assets/5824556/16107343/179d2352-339c-11e6-96b0-6a37eace4af6.png)

**Comment by thelton** [comment]
Sorry, works great... still getting used to magento2 and just needed to run setup:upgrade
