### ISSUE TITLE
Authorize.net failures after install

### ISSUE THREAD

**Issue by leesimple** [bitExpert/magento2-force-login#109]
Just a note - we noticed that after installing this plugin that successful Authorize.net charges would result in an error being shown upon checkout.  All the orders were still entered into Magento (v2.2.2) and the charges were successful at Authorize.net.  However, the error "Attention: Something went wrong, please contact the seller" would appear after a bit of a pause.

To correct this, we added "/authorizenet" as a whitelisted directory - and it now works fine.

Just wanted to share this for others who may encounter the same problem.

**Comment by websharp** [comment]
Hi @leesimple ,

thank you very much for sharing this information!
@shochdoerfer maybe a FAQ section is a good way to place such information and make it visible for others?

Best regards!

**Comment by shochdoerfer** [comment]
Done. I quickly added a [wiki page](https://github.com/bitExpert/magento2-force-login/wiki), we might change this later or provide a "better" solution.
