### ISSUE TITLE
Magento 2.1 compatibility

### ISSUE THREAD

**Issue by agoeurysky** [bitExpert/magento2-force-login#11]
Hi,

the `composer.json` (`"magento/module-customer": "100.0.*"`) is not compatible with Magento 2.1.

Is there a future release that will be compatible with Magento 2.1 soon ?

Thanks.

**Comment by websharp** [comment]
hi @agoeurysky,

we will look into this definitly, need to check the backward incompatible changes of the current release candidate and run some tests.
