### ISSUE TITLE
CMS pages not redirecting when Varnish is used

### ISSUE THREAD

**Issue by robmacecs** [bitExpert/magento2-force-login#113]
It seems that varnish returns the page before your module can check if it should redirect. 

Setup is M2.1.10 using nginx for HTTPS termination, passing to Varnish, then back to NGINX and Magento

Request flow:
HTTPS -> Nginx -> Varnish -?-> Nginx -> PHP-FPM/Magento

I believe this is a correct implementation of Magento, Nginx, Varnish and SSL termination.
Is there some way I can set up the module or change the Varnish configuration so that all pages check your module's logic first? Or is this a fundamental problem with using Varnish cache with your module?

**Comment by robmacecs** [comment]
Just to be clear as well, your module worked perfectly on dev, it is only since moving to a production/staging environment behind Varnish that this seems to be a problem, and it only seems to affect CMS pages and the homepage

**Comment by shochdoerfer** [comment]
I guess it depends how aggressively Varnish is configured to cache the pages. If you have configured it to cache everything it is clear that the requests will be answered first by Varnish and will never reach Magento and thus our module. Not sure if you can exclude the pages that are protected from being cached, that would be an easy fix then, but this might turn your Varnish instance into a simple proxy putting all the load back on Magento.

Maybe we need some kind of API endpoint that Varnish could query to find out if the page can be cached or not or if Varnish can deliver the cached version of the page or not.

What do you think?

**Comment by websharp** [comment]
Or maybe a hint in the HTTP Headers or Cookies may indicate Nginx before calling Varnish to choose between a call to varnish or directly link to Magento. However, I do not know, how this will influence the response / behaviour of Magento itself due to its explicit configuration and integration of Varnish.

**Comment by robmacecs** [comment]
Hi both,

I believe this is the purpose of "Magento\Framework\App\Http\Context" getVaryString and the eventual X-Magento-Vary sha1 in the headers, although having taken a quick look, the customer group and logged in status should already be a part of this . I need to take another look to see why exactly this is being ignored, whether it lies in the Varnish setup itself or your module or not, sorry I don't have more detail just yet.

I will be looking into this today and will update this issue with my findings. Obviously if you get chance sooner than I do anything you find would be much appreciated

Thanks for you time so far

**Comment by shochdoerfer** [comment]
@robmacecs any news on that matter? I just came across [this blogpost](https://maxchadwick.xyz/blog/customers-being-logged-in-to-wrong-account-in-magento) and was remindes of this issue.

**Comment by robmacecs** [comment]
@shochdoerfer no more information currently. We still have this issue but it was deemed low priority for now (Currently it just means that CMS content is available on the Wholesale site that ought to be logged in only access, but browsing to the catalog will redirect to login)

Thanks for the link, we do no use engintron caching as referenced on that post, but I think the concept agrees with the fact, it is probably over-active varnish configuration that is the cause rather than your module.

I think it would be okay to close this issue if you would like? Although it would probably be a good idea for me to post any fix I can for people finding this later? (or perhaps to add a note to the readme once the fix/cause is discovered?) How would you like to proceed?

**Comment by shochdoerfer** [comment]
Thanks. I'll close the issue for now, you can filter for closed issues to find it again. The issue won't get deleted, hopefully ;)
