### ISSUE TITLE
Redirecting back to login page

### ISSUE THREAD

**Issue by mikemunevar** [bitExpert/magento2-force-login#115]
Hello Stephen, 
I have a plugin that allows the user to login to a backend for managing their vendor account.  After the vendor logs in, the URL changes to /csmarketplace/vendor.

I added /csmarketplace/vendor as a whitelist regex rule, but it keeps on taking me back to the vendor login page. How can I prevent the plugin from doing this?

**Comment by shochdoerfer** [comment]
Hard to say without seeing the configuration you have done. Could you send me a screenshot (via email) of your configuration - the edit screen of the rule? You can find my email address on my public GitHub profile page.

**Comment by mikemunevar** [comment]
Ok I will send it to you in an email.
