### ISSUE TITLE
Deleted White list pages still active

### ISSUE THREAD

**Issue by MrPaperArtsy** [bitExpert/magento2-force-login#116]
Hi. I have installed force login on a new install of Magento 2.2.4. I have a wholesale store and don't want new customers registering themselves. So in the white list tab I deleted the entry page customer/account/create.

But when I navigate to the home page I can still click create new account and it takes me to the Create New Customer Account Page.

How do I fix this

Thank you.

**Comment by shochdoerfer** [comment]
Have you enabled the module in `Stores > Configuration > Customers > Customer Configuration > Force Login` by setting the `Enable module` option to `Yes`?

**Comment by shochdoerfer** [comment]
Found the "problem", we have another rule called "Customer Account Dashboard". Due to it's nature of being a regex rule, this will also match the `customer/account/create` route and thus whitelist it. Maybe you need to experiment a bit which routes to whitelist and which not to.

**Comment by MrPaperArtsy** [comment]
Yes I had the module enabled. I have just deleted the Customer Account Dashboard Rule and that has fixed the problem.
Thank you.
