### ISSUE TITLE
after login, can't browse products, all link redirect to coutomer/account page.

### ISSUE THREAD

**Issue by Pooofor** [bitExpert/magento2-force-login#120]
When this extension is enabled, after login, the only available page is customer/account page. I can't go to any products, all redirect to account page.

When this extension is disabled, all work fine.

**Comment by shochdoerfer** [comment]
Hi, thanks for opening this issue. What you describe is actually the use case of this module. After enabling the module, any non-loggedin user should not be able to visit the site. You are able to define a whitelist (=list of pages that should be visible) in the Magento backend.

**Comment by Pooofor** [comment]
If a customer is not logged in, it shows the login page. This is working
fine. However, after a customer is logged, the only page s/he can go is the
customer/account page, no matter which product/category the logged in
customer click.  In other word, before login, a customer will get the login
page, after logged in, a customer will only get the customer/account page.
