### ISSUE TITLE
Can't browse products after login

### ISSUE THREAD

**Issue by Pooofor** [bitExpert/magento2-force-login#121]
If a customer is not logged in, it shows the login page. This is working
fine. However, after a customer is logged, the only page s/he can go is the
customer/account page, no matter which product/category the logged in
customer click.  In other word, before login, a customer will get the login
page, after logged in, a customer will only get the customer/account page.

**Comment by shochdoerfer** [comment]
Thanks for clarification, issue #120 sounded like you were not aware of what the module would be capable of doing.

Do you have more information for me like with Magento version are you running, which version of the module is installed and anything else that could be relevant like are you using Varnish?

**Comment by Pooofor** [comment]
This is brand new installation of Magento 2.2.4, force-Login version 3.0.2.
There are three other extensions installed: onepagecheckout,
savedcreditcard, and customer_activation. Thanks.

**Comment by shochdoerfer** [comment]
Would you mind and try disabling those module, one by one to see if any of those cause side-effects?

**Comment by Pooofor** [comment]
The module is disabled currently. Everything works fine after it is turned
off.

**Comment by websharp** [comment]
Hi @Pooofor ,

not sure, but this may related to the module customer_activation. Would be nice to know, if the Force Login Module works, if the _customer_activation_ Module is disabled.

Best regards

**Comment by shochdoerfer** [comment]
Since we haven't gotten any more feedback for quite a while, I'll close this issue. Feel free to open it again with more information regarding the source of the problem.
