### ISSUE TITLE
404 not found type response not working

### ISSUE THREAD

**Issue by scottw-finao** [bitExpert/magento2-force-login#124]
I'm not sure if this is covered somehow in the plugin, but if you enter a url that does not exist (and thus is not found) instead of redirecting to a 404 error, it redirects to the login.

e.g. a url like
https://mysite.com/some-url/that-goes/nowhere/

pops up a login before displaying the 404 error

**Comment by websharp** [comment]
Hi @scottw-finao ,

maybe this is a duplicate to #83 . We need to know a little bit more about your installment environment. Which Magento version do you use? Which version of the module?
Is this may be related to a caching problem?

Best regards

**Comment by scottw-finao** [comment]
It may be possible. I tried already adding a 'no-route' entry with a variety of regex (/no-route static, no-route static, .*no-route.*, etc) but wasn't able to change the behavior.
It's unclear from that ticket what to try? Suggestions appreciated.

**Comment by websharp** [comment]
Hi @scottw-finao 

does your issue still remain? Or can the issue be closed? If you have any further issues, you could also reopen this issue again or open a new one.

Best regards!

**Comment by shochdoerfer** [comment]
I'll close the issue for now as there hasn't been activity for quite a while.
