### ISSUE TITLE
RegExp for negative lookahead

### ISSUE THREAD

**Issue by shmshrbali** [bitExpert/magento2-force-login#126]
Magento Version : CE 2.1.12

I intend to use this plugin to only block 1 page. rest are to be whitelisted. instead of going through all pages i decided to use a negative lookahead REGEX something like this:

`^((?!string).)*$`

### Expected result
/string/ only this should not be whitelisted

### Actual result
/string/ is visible without logging in

Am i doing something wrong here? or is there a simpler method for this that i'm missing?

**Comment by websharp** [comment]
Hi @shmshrbali ,

thank your for the feedback. Need to look into the current implementation of the regex strategy if the lookahead is supported by the used library. Also would be best to write a unit test to cover the case.

Would be glad if you want to contribute with a pull request, will take me some time to start looking into this.

Best regards
