### ISSUE TITLE
Would be blocking use account creation in the scope of the module?

### ISSUE THREAD

**Issue by amenk** [bitExpert/magento2-force-login#127]
We have an invite-only shop. Would it be in scope of the module to block also to implement such a thing:

https://magento.stackexchange.com/a/168151/81

Then I would make a pull request ...

**Comment by amenk** [comment]
Actually there is already a FOSS module for this: https://github.com/deved-it/magento2-disable-customer-registration
so better leave it there?

**Comment by websharp** [comment]
Hi @amenk 

thanks for the feedback and the thoughts. Currently, you can remove the registration page from the whitelist, so no customer would be able to register on their own. Alternativly, you could use another module to explicitly disable registration.

Best regards

**Comment by amenk** [comment]
It would be still available via API then ...

**Comment by shochdoerfer** [comment]
@websharp do we also want to disable API calls with this module? Would that be a use case for us?

**Comment by amenk** [comment]
Oh you, don't ? :D 
If the use case is, that a shop catalog should be only visible via login, data should not be leaked via APIs though I think

**Comment by amenk** [comment]
#128
