### ISSUE TITLE
Whitelist Admin Url

### ISSUE THREAD

**Issue by sja87** [bitExpert/magento2-force-login#129]
How can I whitelist my adminpage URL?

I use https://www.example.com/controlcenter for my admin page

I try this:
<img width="1407" alt="bildschirmfoto 2018-10-04 um 16 29 38" src="https://user-images.githubusercontent.com/4973582/46481044-be172100-c7f2-11e8-9791-9cb6ffd33ab1.png">

**Comment by websharp** [comment]
Hi @sja87 ,

do you experience a redirect on this defined url? The re-routing process is hooked into the frontend routing process, so it should not effect the backend url call.
Expectation is you are not required to define the admin url as a whitelist rule. If the redirect happens non the less, there may be a sideffect we need to cover.

Best regards!

**Comment by websharp** [comment]
Hi @sja87 

has your issue been resolved? Can the issue be closed? If you have any further issues, you could also reopen this issue again or open a new one.

Best regards!

**Comment by shochdoerfer** [comment]
No reaction since October, closing the issue for now.
