### ISSUE TITLE
How we access home page without login.

### ISSUE THREAD

**Issue by 29sunil** [bitExpert/magento2-force-login#130]
Hello Team

I have installed this extension in Magento2.2.6. But after enable this extension website is open on the customer login page. For example when we open website URL in browser tab then it shows customers login page. But we want to show home page instead of the login page. 
Errors: https://prnt.sc/l59cuj

Thanks

**Comment by websharp** [comment]
Hi @29sunil 

has your issue been resolved? Can the issue be closed? If you have any further issues, you could also reopen this issue again or open a new one.

Best regards!

**Comment by shochdoerfer** [comment]
No reaction since November, closing the issue for now.
