### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by davidwindell** [bitExpert/magento2-force-login#135]
It seems like there have been quite a few bug fixes since the last release in 2017 (v3.0.1).

Can you push out a new release for those of us not using `dev-master` in composer?

Thanks

**Comment by shochdoerfer** [comment]
@davidwindell sure ;) Did not realize that the last release is *that* old. Would want to wait until we can merge #134 and then create a new release.

Thank you for not depending on `dev-master` :)

**Comment by davidwindell** [comment]
Awesome thanks!

**Comment by shochdoerfer** [comment]
Done ;) Marketplace will also be updated soonish.
