### ISSUE TITLE
Support for Magento 2.3

### ISSUE THREAD

**Issue by lracicot** [bitExpert/magento2-force-login#138]
Support for Magento 2.3

### Preconditions
PHP version : 7.2.13
Magento Version : 2.3 CE
Force Login Module Version : 3.1.0
Third party modules : None

### Steps to reproduce
1. `composer require bitexpert/magento2-force-customer-login`

### Expected result
1. It should install bitexpert/magento2-force-customer-login

### Actual result
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for magento/product-community-edition 2.3.0 -> satisfiable by magento/product-community-edition[2.3.0].
    - bitexpert/magento2-force-customer-login 3.1.0 requires magento/module-customer ~100.1|~101.0 -> satisfiable by magento/module-customer[100.1.0, 100.1.1, 100.1.2, 100.1.3, 100.1.4, 100.1.5, 100.1.6, 100.1.7, 100.1.8, 101.0.0, 101.0.1, 100.1.9, 100.1.10, 101.0.2, 100.1.11, 101.0.3, 100.1.12, 101.0.4, 101.0.5, 100.1.13, 100.1.14, 101.0.6, 100.1.15, 101.0.7].
    - Can only install one of: magento/module-customer[102.0.0, 100.1.0].
    - Can only install one of: magento/module-customer[102.0.0, 100.1.1].
    - Can only install one of: magento/module-customer[102.0.0, 100.1.2].
    - Can only install one of: magento/module-customer[102.0.0, 100.1.3].
    - Can only install one of: magento/module-customer[102.0.0, 100.1.4].
    - Can only install one of: magento/module-customer[102.0.0, 100.1.5].
    - Can only install one of: magento/module-customer[102.0.0, 100.1.6].
    - Can only install one of: magento/module-customer[102.0.0, 100.1.7].
    - Can only install one of: magento/module-customer[102.0.0, 100.1.8].
    - Can only install one of: magento/module-customer[102.0.0, 101.0.0].
    - Can only install one of: magento/module-customer[102.0.0, 101.0.1].
    - Can only install one of: magento/module-customer[102.0.0, 100.1.9].
    - Can only install one of: magento/module-customer[102.0.0, 100.1.10].
    - Can only install one of: magento/module-customer[102.0.0, 101.0.2].
    - Can only install one of: magento/module-customer[102.0.0, 100.1.11].
    - Can only install one of: magento/module-customer[102.0.0, 101.0.3].
    - Can only install one of: magento/module-customer[102.0.0, 100.1.12].
    - Can only install one of: magento/module-customer[102.0.0, 101.0.4].
    - Can only install one of: magento/module-customer[102.0.0, 101.0.5].
    - Can only install one of: magento/module-customer[102.0.0, 100.1.13].
    - Can only install one of: magento/module-customer[102.0.0, 100.1.14].
    - Can only install one of: magento/module-customer[102.0.0, 101.0.6].
    - Can only install one of: magento/module-customer[102.0.0, 100.1.15].
    - Can only install one of: magento/module-customer[102.0.0, 101.0.7].
    - magento/product-community-edition 2.3.0 requires magento/module-customer 102.0.0 -> satisfiable by magento/module-customer[102.0.0].
    - Installation request for bitexpert/magento2-force-customer-login ^3.1 -> satisfiable by bitexpert/magento2-force-customer-login[3.1.0].
```

**Comment by shochdoerfer** [comment]
Sadly the current version is only working for 2.2, mainly due to time constraints we were not able to check if there are problems running the module with 2.3.

**Comment by kevingimbel** [comment]
@shochdoerfer Is there any way we could help with testing? We tried to upgrade a Magento shop to 2.3 and this module is the only thing that blocks the update.

**Comment by shochdoerfer** [comment]
@kevingimbel Currently I simply can't find the spare time to work on this, sorry. Someone started to migrate the module to 2.3 in #138 but unfortunately some tests fail due to incompatibilities of Magento 2.2 and 2.3. If you could check what needs to be changed and provide fixes, I'd be happy to review and merge them. 

Thanks for using our module!

**Comment by kevingimbel** [comment]
@shochdoerfer my colleague @drahreg created a pull request https://github.com/bitExpert/magento2-force-login/pull/140 based on https://github.com/bitExpert/magento2-force-login/pull/139

We fixed the tests, they were failing because because the Store Interface had changed and two methods (`getIsActive` and `setIsActive`) were missing in the mock.

If that's all that is needed can you release a new version?

**Comment by shochdoerfer** [comment]
@kevingimbel @drahreg awesome! Thank you. Did you also test it with a real 2.3 instance? Anything noticed that did not work properly? :)

**Comment by kevingimbel** [comment]
@shochdoerfer not yet, but we'll update ASAP after the release :D 

Since the tests are passing and the only issue was a difference with the Interface I'd assume everything else works - Noewt in https://github.com/bitExpert/magento2-force-login/pull/139#issuecomment-455136565 also mentions that it works. 

> Module seems to be running smoothly on 2.3

**Comment by drahreg** [comment]
@shochdoerfer 
> Did you also test it with a real 2.3 instance?

No we did not. But maybe we can make a pre-release so i can upgrade Magento to 2.3 and then i could have a look if there are some problems.

**Comment by shochdoerfer** [comment]
Sounds like a plan. Trying to that later today.

**Comment by lracicot** [comment]
I haven't had the time to fix the tests, but my current fork works well for our use case. If someone can help fix it, would be appreciated because I'm far from being a magento expert. In the meantime @kevingimbel you may use my fork in composer, but it's a bit slower for `composer update`:

```

"require": {
        "bitexpert/magento2-force-customer-login": "dev-patch-1",
},
"repositories": {
        "force-login": {
            "type": "vcs",
            "url": "https://github.com/lracicot/magento2-force-login"
        },
}
```

**Comment by shochdoerfer** [comment]
Fixed with #139, #140.

**Comment by shochdoerfer** [comment]
Release created. Let us know if you run into issues with Magento 2.3. And ideally provide a fix ;)

**Comment by magentodallas** [comment]
Can I get in on this possibly? Current Version 3.0.1 need 3.0.2 
![11](https://user-images.githubusercontent.com/4370729/53761627-a3250780-3e8b-11e9-8464-2398eebbb424.JPG)

**Comment by philippsander** [comment]
> Can I get in on this possibly? Current Version 3.0.1 need 3.0.2
> ![11](https://user-images.githubusercontent.com/4370729/53761627-a3250780-3e8b-11e9-8464-2398eebbb424.JPG)

please execute "bin/magento setup:upgrade"
