### ISSUE TITLE
Add varnish ESI urls to whitelist

### ISSUE THREAD

**Issue by pczerkas** [bitExpert/magento2-force-login#141]
When using Varnish FPC, menu block on url /customer/account/logoutSuccess/ (which is requested by Varnish from the backend as ESI fragment) is not whitelisted by ForceCustomerLogin. Menu is blank on this url.

Please add to default whitelist in ForceCustomerLogin following Magento url:
/page_cache/block/esi/blocks/

### Preconditions

Magento Version :

Force Login Module Version :

Third party modules :

### Steps to reproduce

1.
2.
3.

### Expected result

1.

### Actual result

1. [Screenshot, logs]

**Comment by shochdoerfer** [comment]
Thanks for opening this issue. Mind sending a PR with a patch for this?
