### ISSUE TITLE
bitexpert_forcelogin_whitelist doesn't exist

### ISSUE THREAD

**Issue by codelinesweb** [bitExpert/magento2-force-login#152]
Version3.20 is not working

### Preconditions

Apache .4
PHP 7.2

Magento Version : 2.3.1

Force Login Module Version : 3.2.0

Third party modules :

### Steps to reproduce

1. I installed the module with the composer
2. The Backend section works except whitelist settings

### Expected result

1. FRONT PAGE ERROR
2 exception(s):
Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sportxte_mageb2b.mg1i_bitexpert_forcelogin_whitelist' doesn't exist, query was: SELECT `main_table`.* FROM `mg1i_bitexpert_forcelogin_whitelist` AS `main_table` WHERE (`store_id` IN(0, 1))
Exception #1 (PDOException): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sportxte_mageb2b.mg1i_bitexpert_forcelogin_whitelist' doesn't exist

Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sportxte_mageb2b.mg1i_bitexpert_forcelogin_whitelist' doesn't exist, query was: SELECT `main_table`.* FROM `mg1i_bitexpert_forcelogin_whitelist` AS `main_table` WHERE (`store_id` IN(0, 1))
<pre>#1 Magento\Framework\DB\Statement\Pdo\Mysql->_execute() called at [vendor/magento/zendframework1/library/Zend/Db/Statement.php:303]
#2 Zend_Db_Statement->execute() called at [vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php:480]
#3 Zend_Db_Adapter_Abstract->query() called at [vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php:238]
#4 Zend_Db_Adapter_Pdo_Abstract->query() called at [vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:542]
#5 Magento\Framework\DB\Adapter\Pdo\Mysql->_query() called at [vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:617]
#6 Magento\Framework\DB\Adapter\Pdo\Mysql->query() called at [vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php:737]
#7 Zend_Db_Adapter_Abstract->fetchAll() called at [vendor/magento/framework/Data/Collection/Db/FetchStrategy/Query.php:21]
#8 Magento\Framework\Data\Collection\Db\FetchStrategy\Query->fetchAll() called at [vendor/magento/framework/Data/Collection/AbstractDb.php:778]
#9 Magento\Framework\Data\Collection\AbstractDb->_fetchAll() called at [vendor/magento/framework/Data/Collection/AbstractDb.php:674]
#10 Magento\Framework\Data\Collection\AbstractDb->getData() called at [vendor/magento/framework/Data/Collection/AbstractDb.php:577]
#11 Magento\Framework\Data\Collection\AbstractDb->loadWithFilter() called at [vendor/magento/framework/Data/Collection/AbstractDb.php:562]
#12 Magento\Framework\Data\Collection\AbstractDb->load() called at [vendor/bitexpert/magento2-force-customer-login/Repository/WhitelistRepository.php:135]
#13 BitExpert\ForceCustomerLogin\Repository\WhitelistRepository->getCollection() called at [vendor/bitexpert/magento2-force-customer-login/Controller/LoginCheck.php:129]
#14 BitExpert\ForceCustomerLogin\Controller\LoginCheck->execute() called at [generated/code/BitExpert/ForceCustomerLogin/Controller/LoginCheck/Interceptor.php:24]
#15 BitExpert\ForceCustomerLogin\Controller\LoginCheck\Interceptor->execute() called at [vendor/bitexpert/magento2-force-customer-login/Controller/LoginRouter.php:54]
#16 BitExpert\ForceCustomerLogin\Controller\LoginRouter->match() called at [vendor/magento/framework/App/FrontController.php:95]
#17 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#18 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#19 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:94]
#20 Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#21 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:73]
#22 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#23 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#24 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#25 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:136]
#26 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#27 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:258]
#28 Magento\Framework\App\Bootstrap->run() called at [index.php:39]
</pre>

Exception #1 (PDOException): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sportxte_mageb2b.mg1i_bitexpert_forcelogin_whitelist' doesn't exist
<pre>#1 Zend_Db_Statement_Pdo->_execute() called at [vendor/magento/framework/DB/Statement/Pdo/Mysql.php:93]
#2 Magento\Framework\DB\Statement\Pdo\Mysql->_execute() called at [vendor/magento/zendframework1/library/Zend/Db/Statement.php:303]
#3 Zend_Db_Statement->execute() called at [vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php:480]
#4 Zend_Db_Adapter_Abstract->query() called at [vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php:238]
#5 Zend_Db_Adapter_Pdo_Abstract->query() called at [vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:542]
#6 Magento\Framework\DB\Adapter\Pdo\Mysql->_query() called at [vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:617]
#7 Magento\Framework\DB\Adapter\Pdo\Mysql->query() called at [vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php:737]
#8 Zend_Db_Adapter_Abstract->fetchAll() called at [vendor/magento/framework/Data/Collection/Db/FetchStrategy/Query.php:21]
#9 Magento\Framework\Data\Collection\Db\FetchStrategy\Query->fetchAll() called at [vendor/magento/framework/Data/Collection/AbstractDb.php:778]
#10 Magento\Framework\Data\Collection\AbstractDb->_fetchAll() called at [vendor/magento/framework/Data/Collection/AbstractDb.php:674]
#11 Magento\Framework\Data\Collection\AbstractDb->getData() called at [vendor/magento/framework/Data/Collection/AbstractDb.php:577]
#12 Magento\Framework\Data\Collection\AbstractDb->loadWithFilter() called at [vendor/magento/framework/Data/Collection/AbstractDb.php:562]
#13 Magento\Framework\Data\Collection\AbstractDb->load() called at [vendor/bitexpert/magento2-force-customer-login/Repository/WhitelistRepository.php:135]
#14 BitExpert\ForceCustomerLogin\Repository\WhitelistRepository->getCollection() called at [vendor/bitexpert/magento2-force-customer-login/Controller/LoginCheck.php:129]
#15 BitExpert\ForceCustomerLogin\Controller\LoginCheck->execute() called at [generated/code/BitExpert/ForceCustomerLogin/Controller/LoginCheck/Interceptor.php:24]
#16 BitExpert\ForceCustomerLogin\Controller\LoginCheck\Interceptor->execute() called at [vendor/bitexpert/magento2-force-customer-login/Controller/LoginRouter.php:54]
#17 BitExpert\ForceCustomerLogin\Controller\LoginRouter->match() called at [vendor/magento/framework/App/FrontController.php:95]
#18 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#19 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#20 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:94]
#21 Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#22 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:73]
#23 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#24 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#25 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#26 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:136]
#27 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#28 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:258]
#29 Magento\Framework\App\Bootstrap->run() called at [index.php:39

### Actual result

1. https://snag.gy/4X6Aip.jpg

ERROR

**Comment by shochdoerfer** [comment]
Thank you for this bug report. Looks like the database changes have not been applied. Did you also run `bin/magento setup:upgrade`?

**Comment by codelinesweb** [comment]
Yes, of course I run
 bin/magento setup:upgrade

Nothing is happening.

EM

joi, 11 apr. 2019, 23:03 Stephan Hochdörfer <notifications@github.com> a
scris:

**Comment by websharp** [comment]
Hi @codelinesweb , the error message suggests the missing table `mg1i_bitexpert_forcelogin_whitelist`.
Can you check, if the table `bitexpert_forcelogin_whitelist` (without the prefix) exists?
Maybe there is an issue with a missing table name preparation in the module.

Best regards

**Comment by codelinesweb** [comment]
Yes, I can check. The table bitexpert_forcelogin_whitelist exist with the prefix which Magento have set it. mg1i_bitexpert_forcelogin_whitelist. No data into table yet. EMTrimis de pe Huawei Mobile-------- Mesajul original --------Subiect: Re: [bitExpert/magento2-force-login] bitexpert_forcelogin_whitelist doesn't exist (#152)De la: websharp Către: bitExpert/magento2-force-login CC: Eugen ,Mention Hi @codelinesweb , the error message suggests the missing table mg1i_bitexpert_forcelogin_whitelist.
Can you check, if the table bitexpert_forcelogin_whitelist (without the prefix) exists?
Maybe there is an issue with a missing table name preparation in the module.
Best regards

**Comment by codelinesweb** [comment]
Hi, The table is there. I reinstall the extension 3.2.0 version then it's OK for now. Force Login is there, whitelist rule is working. I add a new rule for Homepage like how to explain in documentation but I am able to see everything from mai website. Why? Trimis de pe Huawei Mobile-------- Mesajul original --------Subiect: Re: [bitExpert/magento2-force-login] bitexpert_forcelogin_whitelist doesn't exist (#152)De la: websharp Către: bitExpert/magento2-force-login CC: Eugen ,Mention Hi @codelinesweb , the error message suggests the missing table mg1i_bitexpert_forcelogin_whitelist.
Can you check, if the table bitexpert_forcelogin_whitelist (without the prefix) exists?
Maybe there is an issue with a missing table name preparation in the module.
Best regards

**Comment by codewebcluj** [comment]
I followed the steps described below but nothing happens on the main page of the site. Anyone can view the page without being redirected to the login page.
----------------------------
The following example shows, how to add a whitelist entry for the homepage (startpage).
1.	Navigate to the Overview Grid and use the Add Entry button.
2.	Enter Homepage into the text field beside from the Label label.
3.	Enter /?$ into the text field beside from the Url Rule label.
4.	Select All Stores from the selection field beside from the Store label.
5.	Use the Save button in the upper menu. After being redirected to the Overview Grid, the new entry should appear to the list and the systems homepage should be available for guest visitors.
----------------

Thanks!

**Comment by shochdoerfer** [comment]
@codelinesweb What did you do different the second time you installed the module?

@codewebcluj Check if the module is enabled in Store > Configuration > Default Store > Customers > Customer Configuration  > Force Login > Enable Module

**Comment by shochdoerfer** [comment]
Closing this issue due to lack of feedback. Feel free to open a new issue if problems still exist.
