### ISSUE TITLE
"MiBPHP Fatal error:  Interface" on compile

### ISSUE THREAD

**Issue by oobehub** [bitExpert/magento2-force-login#158]
bin/magento setup:di:compile
Repositories code generation... 1/7 [====>-----------------------]  14% 1 sec 70.5 MiBPHP Fatal error:  Interface 'BitExpert\ForceCustomerLogin\Api\Controller\LoginCheckInterface' not found in /chroot/home/domain/domain.com/html/app/code/BitExpert/ForcedCustomerLogin/Controller/LoginCheck.php on line 31

### Preconditions
Magento 2.3
PHP 7.2.14 (cli) (built: Jan 11 2019 13:24:51) ( NTS )
filesystem install (not installed with composer)

Force Login Module Version :3.2.0

Third party modules : none

### Steps to reproduce

1.  Installed module via filesystem
2.  successfully ran bin/magento module:enable BitExpert_ForceCustomerLogin
3.  fails at bin/magento setup:di:compile

### Expected result

1. it should compile

### Actual result

1. Repositories code generation... 1/7 [====>-----------------------]  14% 1 sec 70.5 MiBPHP Fatal error:  Interface 'BitExpert\ForceCustomerLogin\Api\Controller\LoginCheckInterface' not found in /chroot/home/domain/domain.com/html/app/code/BitExpert/ForcedCustomerLogin/Controller/LoginCheck.php on line 31

**Comment by shochdoerfer** [comment]
I think you got a typo in one the folders. In the error message the folder is named `ForcedCustomerLogin` but needs to be named `ForceCustomerLogin`. Could you please rename the folder and check if it works afterwards?

**Comment by oobehub** [comment]
You are correct!  It's interesting that a module can be enabled and disabled from within an incorrectly named folder.  

Thank you for the quick reply.
