### ISSUE TITLE
installation compile error

### ISSUE THREAD

**Issue by ahdee** [bitExpert/magento2-force-login#162]
Hi when I try 
magento setup:di:compile
I'm getting this error, 
```
  [RuntimeException]
  Source class "\BitExpert\ForceCustomerLogin\Repository\WhitelistInterface" for "BitExpert\ForceCustomerLogin\Repository\WhitelistRepository" generation does not exist.

```

I'm not sure why though.  Any clue? 
thanks.

**Comment by shochdoerfer** [comment]
If you downloaded the sources via Marketplace, please check that the directory in app/code is called `BitExpert` and not 'bitExpert'. Somewhere in the docs we have on Marketplace there is a typo. Sorry for any inconvenience.

**Comment by ahdee** [comment]
@shochdoerfer hey thanks. I downloaded from your github source, https://github.com/bitExpert/magento2-force-login/releases/tag/v3.2.0

I named the directory "bitexpert" should I had name it "BitExpert" instead?  
thanks. 
A

**Comment by shochdoerfer** [comment]
Ah ok, I see. Yes, the directory needs to be named "BitExpert". Unfortunately Magento modules need to start with an uppercase letter. In the initial versions of Magento 2 this was not enforced, in some later versions this was changed and we had to adapt it.

**Comment by ahdee** [comment]
thank  you so much. I will try it out. FIY your readme installation has it as "bitexpert"
