### ISSUE TITLE
Language switch problem

### ISSUE THREAD

**Issue by thelogh** [bitExpert/magento2-force-login#164]
### Preconditions

Server Ubuntu 18.04 php PHP 7.2.19-0ubuntu0.18.04.1

Magento Version : CE 2.3.2

Force Login Module Version :3.2.0

Third party modules :

### Steps to reproduce

It is not possible to change the language on a Magento 2.3.2 installation with two store views, enabling the plugin and putting the url /stores/store/redirect in the white list. Selecting the language change on the login page always returns to the login page without changing the language.I make the debug url entered is found correctly, but then in redirect goes wrong.

### Expected result

1.Change language in the store

### Actual result

1. [Screenshot, logs]

**Comment by shochdoerfer** [comment]
Thank you for the bug report. Any chance you could provide a fix for this issue?

**Comment by philippsander** [comment]
can you please try also putting "/stores/store/switch" to the whitelist?

**Comment by shochdoerfer** [comment]
@philippsander will this fix the problem mentioned or is this "just" an additional wish? Mind providing a PR, please? Thanks :)

**Comment by philippsander** [comment]
no this is not additional wish ;-)

It might be a solution to the problem. Switching the language uses 2 routes.

**Comment by shochdoerfer** [comment]
@philippsander would you be able to prepare a PR? A bit too much other stuff on my plate these days...

**Comment by philippsander** [comment]
@thelogh can you verify applying this will fix your problem? then we can close the issue

**Comment by thelogh** [comment]
Then with the last update Merge pull request #165 I saw that it adds statically using Static /stores/store/switch and /stores/store/redirect NOT working.
But putting  /stores/store/switch and /stores/store/redirect in RegEx (All), works all fine.
