### ISSUE TITLE
Password Reset not working

### ISSUE THREAD

**Issue by thelogh** [bitExpert/magento2-force-login#167]
### Preconditions

Magento Version :CE 2.3.2

Force Login Module Version :3.2.0

Third party modules :

### Steps to reproduce

1.Request a password reset, click on the password reset link
xxx.com/it/customer/account/createPassword/?token=XXXXXXXXXXXX
2.
3.

### Expected result

1. After clicking on the link, the reset page should appear
xxx.com/it/customer/account/createpassword/

### Actual result

1. The page remains on xxx.com/it/customer/account/createPassword/?token=XXXXXXXXXXXX and I give this error "This page does not redirect correctly"
![Immagine](https://user-images.githubusercontent.com/52915242/64257514-cbb6b880-cf25-11e9-8207-f2a54d5c7828.png)

**Comment by DanielRuf** [comment]
Hi @thelogh,

thanks for reporting this.
We will check this.

**Comment by HausE13** [comment]
Hello @DanielRuf 
Is there something new on this Issue?

Would like to use the extension on a customer project, but this is a big problem. This problem also appears, when a new customer is created and recieves the mail to set the account password.

Thank you in advance :)

**Comment by tscole** [comment]
I am also being affected by this issue. Is there any eta on a fix?

**Comment by shochdoerfer** [comment]
@HausE13 could you please check if the rule for `/customer/account/createPassword` is using the regex strategy?

**Comment by mwoertler** [comment]
I am having the same issue with module version 4.0.0 ... `/customer/account/createPassword` is using regex (all) strategy.

**Comment by shochdoerfer** [comment]
Maybe the RegexMatcher has some issues with the Get Parameter passed. @mwoertler @HausE13 are you able to debug this? Currently lacking a bit of time to tackle the issue but happy to merge any PR to fix this issue.

**Comment by HausE13** [comment]
Unfortunately I did not have that much time to fix it but maybe I found something...

In BitExpert\ForceCustomerLogin\Controller\LoginCheck there is this if-Statement on Line 149:
```
if ($strategy->isMatch($path, $rule)) {
    return false;
}
```
When I looked at the values, when this statement was true, the dumps showed this:

Value of $path is '/customer/account/createPassword/' but $rule looks like in the screenshot. 

![screenshot_path_rule](https://user-images.githubusercontent.com/53185529/69232783-0080f600-0b8c-11ea-9e43-b055015e203b.png)


For me it looks like, that the wrong rule is used, because the $path for ```/customer/account/createPassword/'``` does match the rule for ```/customer/account/create```

Maybe this helps.

**Comment by websharp** [comment]
@HausE13 You should be able to help yourself out by configuring the `/customer/account/create` and the `/customer/account/createPassword/` each both of them as **static** rules instead of the regex-approach.

**Comment by shochdoerfer** [comment]
@HausE13 Or change the order of the rules, that might also help IIRC. I guess the first rule is too generic and matches. Will check this later.

**Comment by tscole** [comment]
Changing rule to static does not appear to have any effect on my installation.

**Comment by HausE13** [comment]
@websharp Changed these two Rules to static and also the  ```/customer/account/``` rule (and in a further step all rules that contain "customer/account") , but got the same result.

**Comment by websharp** [comment]
@tscole @HausE13 
It seems that the `CreatePassword` Controller Class of the Magento Module `Customer` provokes this indefinitly loop though setting the redirect path to the same Url when called directly with the Token parameter, instead of an exit page. See also `Magento\Customer\Controller\Account\CreatePassword` in line 89 (Magento 2.3.3).

I extended the unit tests for the regex matcher, but it works as expected. So we need to find an explicit way to resolve the issue for the createpassword behaviour.

I created a solution with https://github.com/bitExpert/magento2-force-login/pull/177, so feel free to try it out and give feedback.

**Comment by tscole** [comment]
@websharp the fix appears to work for password resets requested on the front end but not those requested on the backend. From what I can see there are parameter differences. Links generated by a front end request have ?token=XXX where as those generated in admin have ?id=YYY&token=XXX

**Comment by mischabraam** [comment]
@tscole and @websharp the solution in PR #177 works if you alter the regex constant in the `PasswordResetHelper` to the following.

`const CREATE_PASSWORD_DIRECT_URL_SCHEME = '/customer/account/createpassword/\?.*token=';`

**Comment by daniel-ifrim** [comment]
Magento 2.3.2.
I had infinite redirects in createpassword action too.
Fixed it after some time by moving in class
`vendor/bitexpert/magento2-force-customer-login/Controller/LoginCheck.php`

```
// Set Url To redrect ,using standard method of magento
$this->customerSession->setBeforeAuthUrl($url);
```

after whitelist test:
```
// check if current url is a match with one of the ignored urls
/** @var \BitExpert\ForceCustomerLogin\Model\WhitelistEntry $rule */
foreach ($this->whitelistRepository->getCollection()->getItems() as $rule) {
    $strategy = $rule->getStrategy();
    if($strategy) {
        $strategy = $this->strategyManager->get($strategy);
        if ($strategy->isMatch($path, $rule)) {
            return false;
        }
    }
}
```
Don't know of any side effects.
I don't understand why anything must be set if the current action is a whitelisted action.

**Comment by daniel-ifrim** [comment]
This is not related to this issue.
Shouldn't all AJAX requests be whitelisted ?
Like section data requests and not only.

I have this in `BitExpert\ForceCustomerLogin\Controller\LoginCheck::execute()` 
affter is module enable test.
```
if ($this->isAjaxRequest()) {
    return false;
}
```

**Comment by websharp** [comment]
@mischabraam Thank you for your feedback, I added it to the PR.

@daniel-ifrim I am not sure I can follow what issue you have. Maybe open a separate issue for your topic?

**Comment by shochdoerfer** [comment]
@daniel-ifrim could you please check if the version in master branch is also working for you?

**Comment by daniel-ifrim** [comment]
Ok, will try now. Thank you

**Comment by daniel-ifrim** [comment]
@shochdoerfer It worked.
Tested Magento 2.3.2:
- with existing customer account clicked on 'Reset Password' button. Clicked on email link and visted successfully on `customer/account/createpassword/` action. I set a password and than logged in successfully.
- with account created from admin. Did the same as above and it worked.

Thank you

**Comment by shochdoerfer** [comment]
Thank you @mischabraam, @websharp & @daniel-ifrim for helping with this. I just have created version 4.0.1 of the package. Should be installable via Composer soonish.
