### ISSUE TITLE
Use with a SAML extention

### ISSUE THREAD

**Issue by oobehub** [bitExpert/magento2-force-login#169]
This is not an issue.  I'm trying to reach out to the developer about getting this to work with a saml module we are using.  We seem to be able to login with SAML when the module is turned off, but when we enable the module we get an "Invalid Form Key" error on the login page.  I assume there is a path i need to whitelist, and probably more customization than that to get this to work.  Any help is appreciated.

Magento Version : 2.3.1

Force Login Module Version :3.0.4

Third party modules :https://marketplace.magento.com/sixtomartin-onelogin-module-saml2.html

We are happy to pay for custom dev.

**Comment by websharp** [comment]
Hi @oobehub ,

I cross-searched for this message just a bit upfront, so the suggestion I found in general for this isto set PHP setting `max_input_vars` to a higher value like 10000 (in php.ini or .user.ini file).

Can you try and give feedback if this helps?

Best regards!

**Comment by oobehub** [comment]
@websharp  hey!  that was quick. I just requested that the value be increased.  I will report back later today when the host gets back to me.

Thanks!

**Comment by oobehub** [comment]
@websharp max_input_vars are 16384.  This was their original setting.  I bumped up to 20000 but saw the same result.

**Comment by DanielRuf** [comment]
Can you check where the error is thrown and provide some more information from the stacktrace?

**Comment by oobehub** [comment]
We don't seem to get a stack trace.  We see it on the customer login page right after the customer is directed back to us from the identity provider.  or when the customer is directed to us directly from the identity provider.
<img width="456" alt="Screen Shot 2019-10-14 at 8 44 39 AM" src="https://user-images.githubusercontent.com/47894571/66869197-d6c12780-ef6c-11e9-919a-223d9a00f9e2.png">

I have no reports, no exceptions, and nothing in my system.log

**Comment by DanielRuf** [comment]
I guess it is https://github.com/magento/magento2/blob/2.3.1/lib/internal/Magento/Framework/App/Request/CsrfValidator.php#L99

And there is also an exception object, see https://github.com/magento/magento2/blob/2.3.1/lib/internal/Magento/Framework/App/Request/CsrfValidator.php#L101

**Comment by DanielRuf** [comment]
I guess it is https://github.com/magento/magento2/blob/2.3.1/lib/internal/Magento/Framework/App/Request/CsrfValidator.php#L99

And there is also an exception object, see https://github.com/magento/magento2/blob/2.3.1/lib/internal/Magento/Framework/App/Request/CsrfValidator.php#L101

Or https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/Customer/Controller/Account/LoginPost.php#L153

**Comment by DanielRuf** [comment]
Can you check from where the message is coming?

**Comment by oobehub** [comment]
oh! I will force a few more logins and try to get the exception.  I will also find out where it is coming from.  Thank You.

**Comment by oobehub** [comment]
The only thing i can get from any log or report is this: 
main.DEBUG: Request validation failed for action "Magento\Framework\App\Action\Redirect\Interceptor" [] []

This is from my debug.log with all error reporting turned on and the site in developer mode.

**Comment by oobehub** [comment]
We whitelisted all SSO urls and it's now working.  I'm working my way back through the urls to see which ones i can take off the whitelist.  Specifically it seems the ACS url needs to be whitelisted.

**Comment by shochdoerfer** [comment]
@oobehub thanks for the info. Once you have the list, might want to document here so that we can point other users to that list? Would be cool to have a common list of whitelist urls for different modules.
