### ISSUE TITLE
Doesn't work when caching is on

### ISSUE THREAD

**Issue by RameshJhajharia** [bitExpert/magento2-force-login#170]
Login doesn't enforced when full page caching is on. Not working on production environment.
### Preconditions

Enable full page cache.

Magento Version : CE 2.3.2

Force Login Module Version :
3.0.6

Third party modules :

### Steps to reproduce

1. Deploy and enable force login on production
2. Load the page first time and it will work perfectly
3. Now load the same URL on another device or incognito window. Force login doesn't work.

### Expected result

1. Login should be enforced until you login.

### Actual result

1. Once the page is cached , login is not enforced.

**Comment by websharp** [comment]
Hi @RameshJhajharia ,

You may want to test with the current version 3.2.0, which officially supports Magento 2.3.
See also: https://github.com/bitExpert/magento2-force-login/releases/tag/v3.2.0

Best regards

**Comment by shochdoerfer** [comment]
@RameshJhajharia did you try to use the latest version? Does it still not work? Do you only have FPC enabled or also Varnish in front of Magento?

**Comment by RameshJhajharia** [comment]
@shochdoerfer I didn't try it with the latest version, for now, I found a workaround using the cookies and apache2 configurations. I will try it with latest version in a few days.
I was not using Varnish.

**Comment by shochdoerfer** [comment]
Thanks for the update. I'll close the issue for now. If you run into more problems, feel free to open a new issue.
