### ISSUE TITLE
Add PHP 7.3 to version requirement in composer.json

### ISSUE THREAD

**Issue by mirsch** [bitExpert/magento2-force-login#171]
### Preconditions
PHP 7.3

Magento Version : 2.3.3

Force Login Module Version : 3.2.0

### Steps to reproduce
actually you have to use `composer require bitexpert/magento2-force-customer-login --ignore-platform-reqs` to install the Module if you have PHP 7.3 installed
The Module runs fine using PHP 7.3, please add it to PHP Version requirement in composer.json

**Comment by DanielRuf** [comment]
Hi @mirsch,

Thanks for the feedback that it works on PHP 7.3.

Can and do you want to provide a PR for https://github.com/bitExpert/magento2-force-login/blob/master/.travis.yml and https://github.com/bitExpert/magento2-force-login/blob/master/composer.json?

That would be really cool =)
