### ISSUE TITLE
Can not create new password on Magento 2.3.3

### ISSUE THREAD

**Issue by jankovandeventer** [bitExpert/magento2-force-login#178]
### Preconditions

Magento 2.3.3
"bitexpert/magento2-force-customer-login": "^4.0",

Magento Version :
Open Source (CE)

Force Login Module Version : 4.0

Third party modules:
Not a single one that interferes with his process

### Steps to reproduce

1. Install and enable bitexpert
2. Request a new password
3. Click on the create new password link in the email

### Expected result

1. Go to create new password page with form

### Actual result

1. infinite redirect

[Batao.zip](https://github.com/bitExpert/magento2-force-login/files/3977952/Batao.zip)

I created a plugin with a pregmatch on the create password url to bypass the Login Check.
This was the quickest workaround, but I bet you can make a nicer solution in the module itself, by adding a check for the create password on Magento 2.3.3+

Thanks for looking into it, and if I can create a PR with a solution, let me know. Would be happy to contribute.

**Comment by websharp** [comment]
Hi @jankovandeventer ,

did you try and use the new [4.0.1 release](https://github.com/bitExpert/magento2-force-login/releases/tag/v4.0.1) which addresses the issue with the password creation?

Best regards

**Comment by jankovandeventer** [comment]
Hello, must have just missed this release. Will try that.

**Comment by manuelcanepa** [comment]
Maybe `magento/magento-coding-standard` is the problem. I have `magento/magento-coding-standard:~3.0.0` in my composer and `bitexpert/magento2-force-customer-login` was installed on version 4.0.0

**Comment by manuelcanepa** [comment]
My bad, Packagist is not updated https://packagist.org/packages/bitexpert/magento2-force-customer-login

**Comment by DanielRuf** [comment]
https://github.com/bitExpert/magento2-force-login/blob/master/composer.json#L5

cc @shochdoerfer

**Comment by DanielRuf** [comment]
See also https://github.com/bitExpert/magento2-force-login/commit/350b32c7d636990f23d0df296259e47768e111ea vs https://github.com/bitExpert/magento2-force-login/commit/e1485c471ec5e802bcc0d72e8ba3cc270bde78d0

**Comment by DanielRuf** [comment]
In the meantime you can try the Git URL or `dev-master`.

**Comment by shochdoerfer** [comment]
@manuelcanepa my bad, I forgot to update the version information in composer.json. I just released a new version 4.0.2 which is already available via Packagist.
