### ISSUE TITLE
Customers get whoops.... after registering

### ISSUE THREAD

**Issue by mastrip2** [bitExpert/magento2-force-login#180]
Has anyone had any issues with customers getting the "whoops, our bad..." page not found error after registering for a account? It seems like the redirect that is done by default from magento isnt executing when the extension is enabled. If I turn it off the registering works.

Magento ver. 2.3.3 CE
Force Login Module Version : 4.0.2
Third party modules :
Magezon_PageBuilder
Mageplaza_CustomerApproval

### Steps to reproduce

1. Go to account register page and register
2. click register

### Expected result

1. To be redirected back to the customer login page ( customer/account/login )

### Actual result

1. Get error "whoops, our bad" error page
![image](https://user-images.githubusercontent.com/4985505/74766246-fe920600-5252-11ea-81e9-f36fa75f2a23.png)

**Comment by beltoftandersen** [comment]
Getting the same on 2.3.4, which the 4.0.2.

<img width="1161" alt="Skærmbillede 2020-03-14 kl  23 06 21" src="https://user-images.githubusercontent.com/43896943/76691189-99121900-6648-11ea-9383-ac303ea03fdd.png">

Error url: /customer/account/createpost/

**Comment by mastrip2** [comment]
I had used the code from #178 as a reference of code to specifically target the registration url and ignore it. Its probably a better way of fixing this issue but I was under alot of pressure to quickly fix the issue. I'll try and find it and post it here as a fix

**Comment by beltoftandersen** [comment]
> I had used the code from #178 as a reference of code to specifically target the registration url and ignore it. Its probably a better way of fixing this issue but I was under alot of pressure to quickly fix the issue. I'll try and find it and post it here as a fix

Can you provide a more detailed description/guide on how you solved the issue?

Much appreciated!

**Comment by shochdoerfer** [comment]
@mastrip2 can you provide us some code how to fix the issue?

**Comment by mastrip2** [comment]
I downloaded the [Batao.zip](https://github.com/bitExpert/magento2-force-login/files/3977952/Batao.zip) code from issue #178 . Then I browsed to the Plugin/Frontend/BitExpert/ForceCustomerLogin/Controller and edited the LoginCheck.php file. Inside the afterExcute function I added a way to check the current url and see if it was the url I observed to be for creating users. If it was I overrode the default way the extension redirected the user causing the error. Below is the code that im currently using. You just have to fix the namespace since I used a different one then the original.

`
<?php


namespace {New Name Space Here}\Register\Plugin\Frontend\BitExpert\ForceCustomerLogin\Controller;

use Magento\Framework\App\Action\Context;
use Magento\Framework\App\Response\Http as ResponseHttp;

/**
 * Class LoginCheck
 *
 * @package {New Name space Here}\Register\Plugin\Frontend\BitExpert\ForceCustomerLogin\Controller
 */
class LoginCheck
{
    /**
     * @var \Magento\Framework\UrlInterface
     */
    private $url;
    
    /**
     * @var ResponseHttp
     */
    private $response;
    private $request;
    
    
    public function __construct(
         \Psr\Log\LoggerInterface $logger,
         Context $context,
         ResponseHttp $response
        ) {
        $this->logger = $logger;
        $this->url = $context->getUrl();
        $this->response = $response;
        $this->request = $context->getRequest();
     }

    public function afterExecute(
        \BitExpert\ForceCustomerLogin\Controller\LoginCheck $subject,
        $result
    ) {
        $this->logger->info('scanning url');
        $url = $this->url->getCurrentUrl();
        
        $this->logger->info($url);
        if($this->request->isPost()){
            return false;
        }
        
        if (strpos($url, 'customer/account/createpost')!== false) {
            $this->logger->info('matched');
            $this->response->setNoCacheHeaders();
            $this->response->setRedirect('/customer/account');
            $this->response->sendResponse();
            return true;//it matched the register redirect
        }
        $this->logger->info('do nothing');
        return $result;//let it be
    }
}
`

**Comment by websharp** [comment]
@shochdoerfer @mastrip2 I can add an extended solution as provided for the password reset handling we recently fixed (see https://github.com/bitExpert/magento2-force-login/blob/master/Controller/LoginCheck.php#L148 and https://github.com/bitExpert/magento2-force-login/blob/master/Controller/PasswordResetHelper.php). Maybe some hook / event to loosely couple the logic and allow customized logic to be attached.

**Comment by shochdoerfer** [comment]
@websharp sure, if you have the time to take a look, go ahead. Not sure if we need to make the logic customizable.

**Comment by niekappartmedia** [comment]
This issue is still a thing, after registration we get redirect to createpost url as a GET.
Thats resulting in a 404. The fix above does not quite work how can we redirect back to the login and not de previous url.

**Comment by mastrip2** [comment]
You could redirect to the `customer/account/login` just change the set redirect function (code above)

**Comment by mustafaeyvazvaimo** [comment]
> This issue is still a thing, after registration we get redirect to createpost url as a GET.
> Thats resulting in a 404. The fix above does not quite work how can we redirect back to the login and not de previous url.

Same here

**Comment by websharp** [comment]
@shochdoerfer Sorry for the delay, I provided the suggested fix in #186

**Comment by davidwindell** [comment]
`master` still 404's for us

**Comment by websharp** [comment]
@mastrip2 @mustafaeyvazvaimo @davidwindell we added some fixes to the master, do you mind testing your issue, if everything works fine now or report any new issue occured?

**Comment by bybilvanis** [comment]
> @mastrip2 @mustafaeyvazvaimo @davidwindell we added some fixes to the master, do you mind testing your issue, if everything works fine now or report any new issue occurred?

Seems ok to me. Thanks for the update.

**Comment by mustafaeyvazvaimo** [comment]
> @mastrip2 @mustafaeyvazvaimo @davidwindell we added some fixes to the master, do you mind testing your issue, if everything works fine now or report any new issue occured?

Seems ok to me. Thanks for the update.

**Comment by joeybab3** [comment]
I am still getting this issue in 4.1.0 unfortunately, any ideas why this may be?
