### ISSUE TITLE
 table or view not found

### ISSUE THREAD

**Issue by darpanpatel2018** [bitExpert/magento2-force-login#185]
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'm2.bitexpert_forcelogin_whitelist' doesn't exist, query was: INSERT  INTO `bitexpert_forcelogin_whitelist` (`store_id`,`label`,`url_rule`,`editable`,`strategy`) VALUES (?, ?, ?, ?, ?)

**Comment by jgcabanas** [comment]
I have the same issue. Did you solve it ?

**Comment by jgcabanas** [comment]
Hi, I solved it. My first install (made by downloading the module with gitHub)  failed, but wrote an entry in  the "setup_module" table. Removing it , and doing another setup:upgrade solved the issue. Good luck :)

**Comment by websharp** [comment]
@jgcabanas Closing this issue for now, but if the issue remains occuring, feel free to (re-)open an issue
