### ISSUE TITLE
Paypal Ipn

### ISSUE THREAD

**Issue by mattyl** [bitExpert/magento2-force-login#188]
Could this be blocking paypal IPN?

my paypal express works fine but paypal pro doesn't and i am seeing 301 redirects in the logs

**Comment by websharp** [comment]
@mattyl hm, potentially yeah, but you may be able to add a suitable rule based on RegEx to whitelist those calls from paypal.

**Comment by mattyl** [comment]
yep whitelisting

/paypal/ipn/

seems to do the trick - for those that follow

**Comment by mattyl** [comment]
ok done!

**Comment by shochdoerfer** [comment]
Fixed and merged with #193
