### ISSUE TITLE
white list missing Admin Uri

### ISSUE THREAD

**Issue by xanka** [bitExpert/magento2-force-login#199]
### Preconditions

Magento Version : CE 2.3.6 (tested) but I think this issue still in all version

Force Login Module Version : 4.1.0

Third party modules : None

### Steps to reproduce

1. composer require bitexpert/magento2-force-customer-login 
2. php bin/magento module:enable BitExpert_ForceCustomerLogin
3. php bin/magento setup:upgrade
4. Enable module in Store -> Configuration -> CUSTOMERS -> Customer configuration -> Force Customer Login -> Enable module.

### Expected result

1. Can access into Magento admin login form
### Actual result

1. [Screenshot, logs]
then I active module and create customer account in frontend I cannt access link of magento 2 admin.

**Comment by xanka** [comment]
I think we should add admin URI link into WhiteLis via UpgradeData.php

**Comment by websharp** [comment]
@xanka Hm that is wierd and we should investigate. The component to reroute is actually only in the frontend DI, so it should not redirect in the admin area.

https://github.com/bitExpert/magento2-force-login/blob/master/etc/frontend/di.xml

**Comment by xanka** [comment]
@websharp yes so weird, Then I am installed this module I cannt access magento admin uri. I tested yet in Magento 2.3.6 only access admin uri then add its into whitelist via database

**Comment by shochdoerfer** [comment]
@xanka please check again with the dev-master version of the module and let us know if the error still exists. We will release a new version of the module in the next few days as well.
