### ISSUE TITLE
Secondary view problem redirect

### ISSUE THREAD

**Issue by thelogh** [bitExpert/magento2-force-login#200]
### Preconditions

Magento Version : MAGENTO 2.3.5-P2 CE

Force Login Module Version : 4.1

Third party modules :

### Steps to reproduce

1.the default sore is www.example.com/it
i switch to another view www.example.com/en from the menu
when reload the page  http://www.example.com/en, the page redirect to http://www.example.com/en/en/customer/account/login give the error "The page you requested was not found"

With the old version \Controller\LoginCheck.php dated 16.12.2019 not have this problem
2.
3.

### Expected result

1.

### Actual result

1. [Screenshot, logs]

**Comment by websharp** [comment]
Hi @thelogh thanks for the issue. Can you please check the configuration of the module's "target url" for your storeview and give us feedback to that?

**Comment by shochdoerfer** [comment]
I am not able to reproduce the issue with Magento 2.4.4 and the dev-master version of the module. We added some fixes, maybe one of them also fixes your problem. Feel free to give the dev-master version a try or wait a few days until we release the next version of the module.
