### ISSUE TITLE
Cannot get past /customer/account/loginPost/ when Redirect Customer to Account Dashboard after Logging in is set to "Yes"

### ISSUE THREAD

**Issue by Latitude1969** [bitExpert/magento2-force-login#201]
Magento Version : CE 4.2.1

Force Login Module Version : Release version 4.1.0

When the Force Login Module is turned on I'm not able to redirect customers to their Account Dashboard.

I get a 404 Error on the hhtp://example.com/customer/account/loginPost/  URL.

I have tried to create a whitelist for aal stores on URL:

/customer/account/loginPost/* 

Which does not seem to work.

Could you please help on providing the correct URL for the whitelist?

Thanks in advance.

Fred.

**Comment by shochdoerfer** [comment]
I could not reproduce the mentioned behavior with the dev-master version of this module and Magento 2.4.4. We will release the next version in the next few days, please check again and come back to us if the error is still happening.
