### ISSUE TITLE
404 present in #180 still present in 4.1.0

### ISSUE THREAD

**Issue by joeybab3** [bitExpert/magento2-force-login#207]
I have the latest version (4.1.0) on Magento 2.4.1 and for some reason, I am still experiencing the issues mentioned in #180. 
When registering, I get a 404 but the success message is shown on the 404 pages.

**Comment by visahardik** [comment]
Yes, I am facing the same issue with 4.1.0 and M2.4.2.

**Comment by shochdoerfer** [comment]
I could not reproduce the issue with the dev-master version of the module and Magento 2.4.4. We added a few bugfixes, maybe those have resolved the issue. We'll release the new version of the module in the next few days. Please check again if the error is gone and if not, come back to us.
