### ISSUE TITLE
disable /customer/account/create

### ISSUE THREAD

**Issue by blizam** [bitExpert/magento2-force-login#22]
I don't want customers to be able to create accounts in one of my websites/store views... so I'd like to similarly restrict access to this page... however, this is one of the "hardcoded" paths that I cannot delete from the Whitelist... is there a way to remove it?

**Comment by websharp** [comment]
Hi @blizam, 

to provide you with an adhoc solution I suggest, if you have access to your database, you could change or delete the entry by yourself from the database table (Table name is _bitexpert_forcelogin_whitelist_).

 For the future, I can think of an _reset default rules_ feature and allow the default rules to be changed or deleted.

**Comment by blizam** [comment]
thank you very much for the prompt reply and workaround :) :+1: 

I think an option like that in the future would be definitely be useful... the more control the better I think.
