### ISSUE TITLE
Circular dependency: Magento\Customer\Model\Plugin\CustomerNotification depends on Magento\Customer\Model\Plugin\CustomerNotification and vice versa.

### ISSUE THREAD

**Issue by manishgoswamig** [bitExpert/magento2-force-login#221]
### Preconditions

Magento Version : Magento 2.4.4 EE

Force Login Module Version : 2.0.0

Third party modules : NO

### Steps to reproduce

1. After Magento version upgrade from 2.3.7-p2 to 2.4.4 version.
2. On the customer login page we are getting the below error.

![image](https://user-images.githubusercontent.com/46725562/178913379-b94a3d2c-9ba3-45a4-9969-e24ce3a0498f.png)

### Expected result

1. It should show the customer login form and the login should be as expected.

**Comment by websharp** [comment]
Hi @manishgoswamig - you are stating using the version 2.0.0 of the module? And placed it into the app/code folder. Is this correct? The 2.0 version is not compatible with Magento 2.4 - you would need to upgrade to the newest version (5.0.1)

Best regards
Florian

**Comment by shochdoerfer** [comment]
Please test again with one of the latest releases. If the error still occurs, let us know. Thanks.
