### ISSUE TITLE
Exception #0 (Exception): Deprecated Functionality: strpos(): Non-string needles will be interpreted as strings in the future

### ISSUE THREAD

**Issue by manishgoswamig** [bitExpert/magento2-force-login#222]
### Preconditions

Magento Version : Magento 2.4.4 EE

Force Login Module Version : 5.0.1

Third party modules : NO

### Steps to reproduce

1. After Magento version upgrade from 2.3.7-p2 to 2.4.4 version.
2. On the customer login page we are getting the below error.

![image](https://user-images.githubusercontent.com/46725562/179238739-3f49938e-f6a2-45c5-8933-a786501aeca2.png)

### Expected result

1. It should show the customer login form and the login should be as expected.

**Comment by shochdoerfer** [comment]
Mind testing again with one of the latest releases? Not exactly sure why this happens in your installation. If the error still occurs, let us know.
