### ISSUE TITLE
PHP 8.2 support

### ISSUE THREAD

**Issue by RomanMoshchytskiy** [bitExpert/magento2-force-login#226]
### Preconditions

Magento Version : 2.4.6

Force Login Module Version : 5.1.0

Third party modules : No

### Steps to reproduce

1. After Magento version upgrade to 2.4.6 version.
2. The module cannot be installed via composer when using php 8.2.

### Expected result

1. Successfully installed via composer.

### Actual result

1.  bitexpert/magento2-force-customer-login 5.1.0 requires php ~7.3.0|~7.4.0|~8.1.0 -> your php version (8.2.5) does not satisfy that requirement.

**Comment by shochdoerfer** [comment]
Thanks a lot for opening your first issue. Mind sending a PR to fix this?
