### ISSUE TITLE
Updating PHP version for Magento 2.4.7

### ISSUE THREAD

**Issue by nalinsavaliya** [bitExpert/magento2-force-login#232]
While installing moudule using composer for Magento 2.4.7 and PHP 8.3.4. I am receiving below error
```
Problem 1
    - Root composer.json requires bitexpert/magento2-force-customer-login ^5.3.0 -> satisfiable by bitexpert/magento2-force-customer-login[5.3.0].
    - bitexpert/magento2-force-customer-login 5.3.0 requires php ~8.1.0|~8.2.0 -> your php version (8.3.4) does not satisfy that requirement.
```

### Preconditions
Installing module for Magento 2.4.7 and PHP 8.3.4

Magento Version : 2.4.7
Force Login Module Version : 5.3.0

Third party modules :

### Steps to reproduce
1. Within Magento 2.4.7 and PHP 8.3.4
2. composer require bitexpert/magento2-force-customer-login:^5.3.0

### Expected result
1. It should be installed without error.

### Actual result
1. Throwing below Error
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires bitexpert/magento2-force-customer-login ^5.3.0 -> satisfiable by bitexpert/magento2-force-customer-login[5.3.0].
    - bitexpert/magento2-force-customer-login 5.3.0 requires php ~8.1.0|~8.2.0 -> your php version (8.3.4) does not satisfy that requirement.
```

**Comment by nalinsavaliya** [comment]
I have created PR for this https://github.com/bitExpert/magento2-force-login/pull/233

**Comment by shochdoerfer** [comment]
@nalinsavaliya thank you for your first contribution! Very much appreciated!

**Comment by umizoomi** [comment]
@shochdoerfer, When is a new release expected?

**Comment by shochdoerfer** [comment]
@umizoomi Fixed :) https://github.com/bitExpert/magento2-force-login/releases/tag/v5.4.0
