### ISSUE TITLE
every time redirecting to my account page when i click home page

### ISSUE THREAD

**Issue by sivajik34** [bitExpert/magento2-force-login#26]
After login every time redirecting to my account page when i click home page.
We have configured varnish cache.
Some times if i delete browser cache & refresh varnish it seems working fine.

**Comment by websharp** [comment]
Hi @sivajik34 ,

thank you for your information. To provide offical support for Varnish, I have to dig deeper into the mechanics of Magento2+Varnish first, so this issue may take a while before I can provide a solution.

**Comment by sivajik34** [comment]
More Information.
I'm facing this issue for all cms pages.
I mean if i click any cms page its redirecting to my account page.
if i remove browser cache (no need of refresh varnish) its working fine.
steps to reproduce the issue:
1.with out login: request for any page (3 times or more)
2.then login
3.now click any cms page

**Comment by websharp** [comment]
hi @sivajik34 ,

thanks for the additional information. Sadly I am not able to reproduce your issue at the moment. 
Can you tell me more about your system? Which version of the module do you use? Magento 2.0 or 2.1, CE or EE? 
Does this issue occur in every browser or just in a specifc one, and do you use some specific cache settings or extensions influcencing the cache behaviour of your browser? 
Have you added some rules or are you using the basic setup? Do you use any other extension that may be interfering with the functionality of the Force Login module?

**Comment by sivajik34** [comment]
Magento 2.0 Enterprise ,On every browser I'm facing this issue. no other modules influenced.

**Comment by websharp** [comment]
Hi @sivajik34 ,

it seems the Magento 2.x Enterprise Edition works the Page Cache differently as the Community Edition and this may cause the described problems. We do not have the EE at hand, so it is not possible for us to test the module against it. 
Perhaps you are able to contribute a working solution or if you require some assistance let us gain access to the EE to debug this issue.

**Comment by cowmix88** [comment]
I'm having a similar problem which is caused by the browser caching the 302 redirection response

**Comment by websharp** [comment]
Hi @cowmix88 ,

thank you very much for this contribution, we will look into this.
