### ISSUE TITLE
How to add only home page in whitelist ?

### ISSUE THREAD

**Issue by dungnv** [bitExpert/magento2-force-login#33]
Dear Author,

How to add only home page in whitelist ?

Thanks.

**Comment by websharp** [comment]
Hi @dungnv ,

As I understand your request, I will refer you to issue #30 , for your purpose you can use the value:

> /$

**Comment by mattcoz** [comment]
This isn't working for me.

**Comment by mattcoz** [comment]
Had to use

`^/$`

It apparently checks for the whitelisted path _anywhere_ in the requested path. This doesn't seem like a good idea to me.

**Comment by websharp** [comment]
Added documentation with the homepage example
