### ISSUE TITLE
Redirect Customer to Account Dashboard after Logging in setting

### ISSUE THREAD

**Issue by cowmix88** [bitExpert/magento2-force-login#35]
You can set this value to No in Configuration > Customers > Customer Configuration > Login Options
and the expected result is that after login the user should be returned to the original page they were on, but with this plugin enabled it seems to always send them to the My Account page after login.

**Comment by websharp** [comment]
Hi @cowmix88 ,

thank you for the information. We need to think about how to include this configuration setting.

For the moment, the redirect target url ist fixed to _customer/account/login_ and not respecting any other configuration. @carlowens has provided a pull request to redefine the target url by the administration area (https://github.com/bitExpert/magento2-force-login/pull/29).

We are finalizing the feature to setup more then one target url in relation to different store, storeviews and websites, so you could use the provided pull request or you should be able to override the DI configuration with the following statement in your _di.xml_:

```
<type name="\bitExpert\ForceCustomerLogin\Controller\LoginCheck">
        <arguments>
            <argument name="targetUrl" xsi:type="string">CUSTOM/TARGET/URL</argument>
        </arguments>
</type>
```

**Comment by mekakkar** [comment]
Hi Team,

I am aslo facing the same issue. everytime the i am redirected to same page. I tried changing the cache from Varnish to default but issue still persist. I am on Magnto 2.1 CE

**Comment by websharp** [comment]
Hi @mekakkar ,

have you tried to override the DI as a workaround for the moment?

**Comment by mekakkar** [comment]
Hi @websharp 

I tried installing this extension in 3 different setup of Magento 2 on windows environment. I am not sure of the reason but it started working properly after sometime, Now i am facing the issue in  only 1 setup. Ill try to override and revert back in couple of days. Thanks
