### ISSUE TITLE
Cannot login to admin after installation

### ISSUE THREAD

**Issue by mtjohnson** [bitExpert/magento2-force-login#36]
I do see that the module was installed successfully because the homepage redirects to login, but when I attempt to sign into the admin backend it will only reload the login screen (without any error appearing).

I've cleared cache / cookies / etc. Sometimes when I've done that instead of the Login screen reappearing I see a "too many redirect loops" error, but that is intermittent.

I'm using the bitnami magento 2 AWS image. Is there a whitelist I need to add for the Admin side?

**Comment by philippsander** [comment]
Does it work if you disable the module?

**Comment by cookiekiller** [comment]
@mtjohnson I couldn't verify this problem neither with 2.0.* nor with 2.0.*. I even tried it with obscrube admin_f45as urls and so on.

**Comment by websharp** [comment]
Hi @mtjohnson ,

closing this issue. If you encounter your problem any further, please re-open and list your used version of Magento 2 (2.0 or 2.1; CE or EE) and your current list of whitelist rules.
