### ISSUE TITLE
Conflict with extension https://amasty.com/improved-layered-navigation-for-magento-2.html

### ISSUE THREAD

**Issue by dungnv** [bitExpert/magento2-force-login#38]
Hi,

Can you help us resolved this issue:
```
1 exception(s):
Exception #0 (LogicException): Circular dependency: Magento\Catalog\Model\Layer\Category depends on Magento\Catalog\Model\Layer\Category\StateKey and vice versa.

Exception #0 (LogicException): Circular dependency: Magento\Catalog\Model\Layer\Category depends on Magento\Catalog\Model\Layer\Category\StateKey and vice versa.
#0 /vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Catalog...', Array)
#1 /vendor/magento/module-catalog/Model/Layer/Resolver.php(70): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Catalog...')
#2 /app/code/Amasty/Shopby/Model/Resolver.php(38): Magento\Catalog\Model\Layer\Resolver->get()
#3 /app/code/Amasty/Shopby/Plugin/RouteParamsResolverPlugin.php(30): Amasty\Shopby\Model\Resolver->get()
#4 /vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): Amasty\Shopby\Plugin\RouteParamsResolverPlugin->__construct(Object(Magento\Catalog\Model\Layer\Resolver), Object(Amasty\Shopby\Model\Resolver), Object(Magento\Framework\Url\QueryParamsResolver), Object(Amasty\Shopby\Model\Request))
#5 /vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(89): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Amasty\\Shopby\\P...', Array)
#6 /vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Amasty\\Shopby\\P...')
#7 /vendor/magento/framework/Interception/PluginList/PluginList.php(232): Magento\Framework\ObjectManager\ObjectManager->get('Amasty\\Shopby\\P...')
#8 /vendor/magento/framework/Interception/Chain/Chain.php(65): Magento\Framework\Interception\PluginList\PluginList->getPlugin('Magento\\Framewo...', 'Amasty_Shopby::...')
```

Thanks.

**Comment by cookiekiller** [comment]
Hi, I don't have the plugin you mentioned to reproduce this behaviour. This stack trace is just about the Amasty plugin and not about ours.

Did you install the Amasty plugin first or force-login first? Can you maybe try installing them the other way?

**Comment by shochdoerfer** [comment]
@dungnv we recently fixed this issue for one of our clients. The source of the problem was found in a theme the client bought. Unfortunately the quality of the theme code was not the best. We were able to fix the problem in the theme. In case you need help, ping me.

**Comment by namratavora** [comment]
Facing same issue

**Comment by shochdoerfer** [comment]
@namratavora same module or a different one?

**Comment by dhrumin44** [comment]
Facing same issue but model different.

`Circular dependency: Magento\Framework\View\Layout depends on Amasty\Shopby\Model\Layer\Cms\Manager and vice versa.`

is there any solution???

**Comment by shochdoerfer** [comment]
@dhrumin44 I don't know this extension, best is to ask the author of the extension to fix this as the error seems to be on their side. We were facing similar issues in the past which badly written themes - themes quickly ported from M1 to M2 with a lot of ObjectManager calls in the template code. Maybe this issue is something similar.

**Comment by Madyo** [comment]
Facing exact same issue @dhrumin44 

Did someone figure out any solution?

**Comment by dhrumin44** [comment]
@Madyo still i can't figure out the issue. if you can find then please share your answer.

**Comment by Madyo** [comment]
@dhrumin44 updating Amasty module "Improved Layered Navigation" solved the problem for us
