### ISSUE TITLE
Sorry, I dont see Forced Login Whitelist after install 

### ISSUE THREAD

**Issue by levasc** [bitExpert/magento2-force-login#39]
I run  composer require bitexpert/magento2-force-customer-login
in the directory of my website, however no menu is displayed

Composer, as I understand, shows it is installed

composer show bitexpert/magento2-force-customer-login
name     : bitexpert/magento2-force-customer-login
descrip. : The Force Login module for Magento2 redirects a storefront visitor to the Magento2 Frontend login page, if the visitor is not logged in. It is possible to configure the whitelisted urls to add custom definitions.
keywords : 
versions : * 1.2.4
type     : magento2-module
license  : Apache License 2.0 (Apache-2.0) (OSI approved) https://spdx.org/licenses/Apache-2.0.html#licenseText
source   : [git] https://github.com/bitExpert/magento2-force-login.git 1ddcef13021843478bfd453fabf66d80482e2f60
dist     : [zip] https://api.github.com/repos/bitExpert/magento2-force-login/zipball/1ddcef13021843478bfd453fabf66d80482e2f60 1ddcef13021843478bfd453fabf66d80482e2f60
names    : bitexpert/magento2-force-customer-login

autoload
files
psr-4
bitExpert\ForceCustomerLogin\ => .

requires
magento/module-customer 100.1.*
php ~5.5.0|~5.6.0|~7.0.0

requires (dev)
phing/phing ^2.8.0
phpunit/phpunit ~5.0
squizlabs/php_codesniffer ^2.3

**Comment by levasc** [comment]
It appeared after upgrade :)

**Comment by shochdoerfer** [comment]
Perfect!
