### ISSUE TITLE
Default add sitemap.xml and robots.txt to whitelist

### ISSUE THREAD

**Issue by miketechtwo** [bitExpert/magento2-force-login#43]
Hi guys,

It would be great if robots.txt and sitemap.xml are default added to the whitelist.
Now you'll get redirect to the customer login page when you go to http://www.example.com/robots.txt.
Google will not be able to index the site since robots.txt is not allowed to visit.
Thank you in advance.

Kind regards,
Mike

**Comment by philippsander** [comment]
Very good idea! thank you!

**Comment by miketechtwo** [comment]
Thank you!
