### ISSUE TITLE
Cannot disable by scope

### ISSUE THREAD

**Issue by maderlock** [bitExpert/magento2-force-login#54]
A common use-case for this extension would be to have trade and direct to customer websites set up, possibly with multiple sites under each. I say this as we've had several clients over the years with this requirement.

To support this, the module just needs to have an enabled/disabled option in the system config. This can then be scoped by website/store without further effort.

**Comment by websharp** [comment]
Hi @maderlock 

many thanks for your contribution. I added #57 PR to match your request and added the specificiation of the target url.
