### ISSUE TITLE
Match home page

### ISSUE THREAD

**Issue by maderlock** [bitExpert/magento2-force-login#55]
I tried entering / as a whitelist to allow the home page to match.

But this seems to match all pages. I think the regex needs to match the specified page and no more. For the start this could just match the part of the request that Magento considers the path, and at the end ignore any query string.

**Comment by maderlock** [comment]
It looks like you are already matching the path, so that's a start. I'll remove the .* at the beginning then.

**Comment by websharp** [comment]
Hi @maderlock 

you should be able to whitelist the homepage with the following rule.

`^/?$`

But I will look into your PR #56 for improving the regex matcher.

**Comment by websharp** [comment]
The regex matcher of PR #56 is failing in the tests, so this would need rework.

Did the mentioned rule work for you? Feel free to reopen, if your issues remain.

**Comment by maderlock** [comment]
I know this is closed, but just to confirm that this solve my issue. Thanks
