### ISSUE TITLE
ACL error when accessing Store Configuration

### ISSUE THREAD

**Issue by adamj88** [bitExpert/magento2-force-login#64]
@websharp we're seeing an error in developer mode on Magento CE 2.1.6 (not sure if this is present on earlier versions).

When trying to access a Store's configuration in the admin side the following error is getting thrown:

```
Invalid XML in file {...}/bitexpert/magento2-force-customer-login/etc/adminhtml/system.xml:
Element 'resource': [facet 'pattern'] The value 'bitExpert::ForceCustomerLogin' is not accepted by the pattern '([A-Z]+[a-zA-Z0-9]{1,}){1,}_[A-Z]+[A-Z0-9a-z]{1,}::[A-Za-z_0-9]{1,}'. Line: 11
Element 'resource': 'bitExpert::ForceCustomerLogin' is not a valid value of the atomic type 'typeAclResourceId'. Line: 11
```

The regex for resources expects the module's vendor name to begin with an uppercase letter, using `bitExpert` causes it to throw the above error.

@chedaroo has submitted a PR for this here: #63

**Comment by websharp** [comment]
Hi @adamj88, 

thank you for the report, the PR is merged to the _master_.
