### ISSUE TITLE
admin system xml file format  error

### ISSUE THREAD

**Issue by sandeepsharma12412** [bitExpert/magento2-force-login#65]
I am tried to setup this module in my magento 2.1.5 v. its enabled prefect but when i am try  to open it its disable label display .also the  admin confiuration getting exception error the system.xml file format is not proper can you help me .
Thanks

**Comment by websharp** [comment]
Hi @sandeepsharma12412,

can you tell me which version of the Module you are using or the composer rule, you are using? We released a RC3 for the v2.0 of the Module, in which the system.xml issue is addressed. Maybe you can try and give feedback, if this has fixed your issue?

**Comment by websharp** [comment]
Hi @sandeepsharma12412 ,

I'm closing this issue. If your problem remains, feel free to reopen this issue again.
