### ISSUE TITLE
Redirect loop

### ISSUE THREAD

**Issue by adamj88** [bitExpert/magento2-force-login#66]
I'm having a problem signing into a customer account with the module enabled on v2.0.0.

With the module enabled on a store view, I'm redirected to `/customer/account/` which redirects me back to `/customer/account/login/` and the loop continues.

This issue is resolved by whitelisting `/customer/account/` which is not present in the default configuration.

**Comment by websharp** [comment]
Hi @adamj88 

thank you for reporting this issue and thanks for the PR!
