### ISSUE TITLE
Activating the module also blocks the backend

### ISSUE THREAD

**Issue by rikwillems** [bitExpert/magento2-force-login#68]
After I activate the module in the backend I'm redirected to the frontend login. The events.xml file should be placed in the frontend directory to fix the issue.

**Comment by websharp** [comment]
Hi @rikwillems ,

thank you for the feedback. We will consider this for the next release.

**Comment by peterjaap** [comment]
This doesn't happen on my installation, so it works fine for me.

**Comment by peterjaap** [comment]
Ok, it did happen on my install. Made PR #71

**Comment by websharp** [comment]
Hi @peterjaap 

thank you for the PR. I will make this a bugfix release on 2.0.
