### ISSUE TITLE
Force login top level system config tab is overkill

### ISSUE THREAD

**Issue by maderlock** [bitExpert/magento2-force-login#73]
It's great that we now have the ability to enable/disable by scope, but system admin is getting unusable with every developer putting in another top level tab.

Any chance that the very small number of config options could be put in as a group under the Customer system config tab?

**Comment by websharp** [comment]
Hi @maderlock ,

I see your point. Interested in providing a PR for this? In other ways, I will provide a change as soon as possible.

**Comment by maderlock** [comment]
I should have made one before when I implemented scoping in a fork. I'll take a look at this when I have a moment - let's see who gets to it first :)

**Comment by websharp** [comment]
Fixed this issue with RC3 of v2.1.0
