### ISSUE TITLE
Upgrade to 2.1 RC2 from 2 breaks backward compatibility of rules

### ISSUE THREAD

**Issue by maderlock** [bitExpert/magento2-force-login#74]
Before 2.1 the assumption was that all rules were regex.
In 2.1 the default is that all rules are static, and seems to apply to all the existing rules.

Therefore in upgrading my current functionality breaks. Can I suggest that even if your default becomes static, all existing rules on upgrade are set to regex to maintain backwards compatibility?

**Comment by websharp** [comment]
Hi @maderlock,

shouldn't be a problem to setup an upgrade for this. Hope to find some time this week to do so. I let you know.

**Comment by websharp** [comment]
Fixed this issue with RC3 of v2.1.0
