### ISSUE TITLE
Un-escaped forward slash.

### ISSUE THREAD

**Issue by jignesh26** [bitExpert/magento2-force-login#80]
Hello,

 I have mulitwebsite, I have to set this module for another website. but when i add the / to whitelist  the homepage it is allowing me to access all pages. 

For example. 
http://test-2.com should be allowed to visit.
http://test-2.com/site should be allowed to visit , here shop is store name.

but / is allowing to access all pages.
when i try to check the #^.*%s/?.*$#i into regular expression checker they are saying the expression have errors. 

Can you help me in that if i want to allow only homepage no other pages.

Thank you.

**Comment by websharp** [comment]
Hi @jignesh26 ,

which version of the module are you using? The [documentation](https://github.com/bitExpert/magento2-force-login#whitelisting) has an example on how to add the rule for the global whitelisting rule related to the homepage. Of course you could also add an additional whitelist entry with the rule value `^/site/?$`.

The current release candidate allows to switch to a static approach as an alternative to the regex definition, maybe this could help you to easily setup your desired environment.

**Comment by jignesh26** [comment]
Hello @websharp ,

 I am using version 2.0.0, I have added the line from the documentation, /?$ to skip the home page but it is allowing all the pages. so as you said i will try to use ^/b2b/?$ but for what about the home page? 

I have check the regular expression online to find out any error and found that expression has error. but i am not sure. 


Thank you in advance.

**Comment by websharp** [comment]
Hi @jignesh26,

you said that you are using this rule:
> /?$

but you need the start line indicator of regex to force the rule to match only with the homepage, and not with everything ending optionally with end slash character. So the correct rule is:

> ^/?$

**Comment by websharp** [comment]
Hi @jignesh26 ,

we released v2.1 of the module. Please try and check if your issue remains. I will close this issue, but if your issue remains, feel free to open again.
