### ISSUE TITLE
It shows blank page when install it on magento 2.2

### ISSUE THREAD

**Issue by thienphucvx** [bitExpert/magento2-force-login#87]
I have tested it on magento 2.2 . After installing, it shows blank page. Do we have new version of it which compatible with magento 2.2 ?

**Comment by websharp** [comment]
Hi @thienphucvx ,

thank you for your feedback. Which version of the module did you try out? The current version v2.2 of the module is compatible with Magento 2.2.

Best regards

**Comment by thienphucvx** [comment]
Is this version ?
https://github.com/bitExpert/magento2-force-login/tree/release/r2.2.0
 I have installed this version : 2.1.0 <module name="bitExpert_ForceCustomerLogin" setup_version="2.1.0"> from this respository.

**Comment by websharp** [comment]
You can either download the current v2.2 release here: https://github.com/bitExpert/magento2-force-login/releases/tag/v2.2.0 and install manually, or if you use _compose_ you should be able to upgrade by running _composer update_

**Comment by thienphucvx** [comment]
Hi,
 Strange. I have installed it and still received the blank page on frontend. When trying to access admin : it shows error "redirected you too many times." 

Have you tried to install it on magento 2.2 ?

![bug_1](https://user-images.githubusercontent.com/4675698/31530443-afa338b2-b00a-11e7-9e8a-c3e99734a5db.png)

**Comment by websharp** [comment]
Hi @thienphucvx ,

maybe you want to try out the new release candidate for v2.3.0 (https://github.com/bitExpert/magento2-force-login/releases/tag/v2.3.0-RC1).

Best Regards

**Comment by websharp** [comment]
Hi @thienphucvx ,

we released the stable candidate for v2.3.0. Hope, this can provide a solution for your issue. I will close this issue for now, but if you encounter any problems, feel free to reopen or create a new issue.

Best regards
