### ISSUE TITLE
Whitelist is Not works for Magento 2.2.0

### ISSUE THREAD

**Issue by gizmocn** [bitExpert/magento2-force-login#91]
I have installed the moduel(v2.3.0-RC1) on Magento 2.2.0, after I enable the module and test it on frontend, it works. great.
My php version is 7.0.22.

However, when I try to access Backend -> Customer -> Whitelist, I got error Message:

1 exception(s):
Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'block', attribute 'class': [facet 'pattern'] The value 'bitExpert\ForceCustomerLogin\Block\Adminhtml\Settings\Whitelist' is not accepted by the pattern '[A-Z][a-zA-Z\d]*(\\[A-Z][a-zA-Z\d]*)*'.
Line: 132

Element 'block', attribute 'class': 'bitExpert\ForceCustomerLogin\Block\Adminhtml\Settings\Whitelist' is not a valid value of the atomic type 'blockClassType'.
Line: 132

Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'block', attribute 'class': [facet 'pattern'] The value 'bitExpert\ForceCustomerLogin\Block\Adminhtml\Settings\Whitelist' is not accepted by the pattern '[A-Z][a-zA-Z\d]*(\\[A-Z][a-zA-Z\d]*)*'.
Line: 132

Element 'block', attribute 'class': 'bitExpert\ForceCustomerLogin\Block\Adminhtml\Settings\Whitelist' is not a valid value of the atomic type 'blockClassType'.
Line: 132

#0 /var/www/html/aaron/vendor/magento/framework/Config/Dom.php(115): Magento\Framework\Config\Dom->_initDom('<layout xmlns:x...')
#1 /var/www/html/aaron/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): Magento\Framework\Config\Dom->__construct('<layout xmlns:x...', Object(Magento\Framework\App\Arguments\ValidationState), Array, NULL, '/var/www/html/a...', '%message%\nLine:...')
#2 /var/www/html/aaron/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#3 /var/www/html/aaron/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Framewo...', Array)
#4 /var/www/html/aaron/vendor/magento/framework/Config/DomFactory.php(42): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Framewo...', Array)
#5 /var/www/html/aaron/vendor/magento/framework/View/Model/Layout/Update/Validator.php(125): Magento\Framework\Config\DomFactory->createDom(Array)
#6 /var/www/html/aaron/vendor/magento/framework/View/Model/Layout/Merge.php(461): Magento\Framework\View\Model\Layout\Update\Validator->isValid('<layout xmlns:x...', 'layout_merged', false)
#7 /var/www/html/aaron/vendor/magento/framework/View/Model/Layout/Merge.php(442): Magento\Framework\View\Model\Layout\Merge->_validateMergedLayout('LAYOUT_adminhtm...', '<head>\n   <css ...')
#8 /var/www/html/aaron/vendor/magento/framework/View/Layout/Builder.php(86): Magento\Framework\View\Model\Layout\Merge->load()
#9 /var/www/html/aaron/vendor/magento/framework/View/Layout/Builder.php(63): Magento\Framework\View\Layout\Builder->loadLayoutUpdates()
#10 /var/www/html/aaron/vendor/magento/framework/View/Page/Config.php(197): Magento\Framework\View\Layout\Builder->build()
#11 /var/www/html/aaron/vendor/magento/framework/View/Page/Config.php(207): Magento\Framework\View\Page\Config->build()
#12 /var/www/html/aaron/vendor/magento/framework/App/View.php(170): Magento\Framework\View\Page\Config->publicBuild()
#13 /var/www/html/aaron/vendor/magento/framework/App/View.php(114): Magento\Framework\App\View->loadLayoutUpdates()
#14 /var/www/html/aaron/app/code/bitExpert/ForceCustomerLogin/Controller/Adminhtml/Manage/Index.php(26): Magento\Framework\App\View->loadLayout()
#15 /var/www/html/aaron/vendor/magento/framework/App/Action/Action.php(107): bitExpert\ForceCustomerLogin\Controller\Adminhtml\Manage\Index->execute()
#16 /var/www/html/aaron/vendor/magento/module-backend/App/AbstractAction.php(229): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#17 /var/www/html/aaron/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#18 /var/www/html/aaron/vendor/magento/framework/Interception/Interceptor.php(138): bitExpert\ForceCustomerLogin\Controller\Adminhtml\Manage\Index\Interceptor->___callParent('dispatch', Array)
#19 /var/www/html/aaron/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): bitExpert\ForceCustomerLogin\Controller\Adminhtml\Manage\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#20 /var/www/html/aaron/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(bitExpert\ForceCustomerLogin\Controller\Adminhtml\Manage\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#21 /var/www/html/aaron/vendor/magento/framework/Interception/Interceptor.php(153): bitExpert\ForceCustomerLogin\Controller\Adminhtml\Manage\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#22 /var/www/html/aaron/generated/code/bitExpert/ForceCustomerLogin/Controller/Adminhtml/Manage/Index/Interceptor.php(26): bitExpert\ForceCustomerLogin\Controller\Adminhtml\Manage\Index\Interceptor->___callPlugins('dispatch', Array, NULL)
#23 /var/www/html/aaron/vendor/magento/framework/App/FrontController.php(55): bitExpert\ForceCustomerLogin\Controller\Adminhtml\Manage\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#24 /var/www/html/aaron/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#25 /var/www/html/aaron/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#26 /var/www/html/aaron/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#27 /var/www/html/aaron/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#28 /var/www/html/aaron/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#29 /var/www/html/aaron/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
#30 /var/www/html/aaron/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))

Any suggest?

**Comment by websharp** [comment]
Hello @gizmocn ,

thank you for your feedback. I suggest, you try out 2.3.0-RC2 (https://github.com/bitExpert/magento2-force-login/releases/tag/v2.3.0-RC2) 

:)

Best regards

**Comment by gizmocn** [comment]
It works now, thanks a lot

**Comment by mattcoz** [comment]
I have the latest 2.3.0 installed and I'm getting this same error.

**Comment by GalacticPlastic** [comment]
New error after updating to 2.3.0 with Composer:

1 exception(s):
Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'block', attribute 'class': [facet 'pattern'] The value 'bitExpert\ForceCustomerLogin\Block\Adminhtml\Manage\Create' is not accepted by the pattern '[A-Z][a-zA-Z\d]*(\\[A-Z][a-zA-Z\d]*)*'.
Line: 127

Element 'block', attribute 'class': 'bitExpert\ForceCustomerLogin\Block\Adminhtml\Manage\Create' is not a valid value of the atomic type 'blockClassType'.
Line: 127

Element 'block', attribute 'class': [facet 'pattern'] The value 'bitExpert\ForceCustomerLogin\Block\Adminhtml\Manage\Create\Submit' is not accepted by the pattern '[A-Z][a-zA-Z\d]*(\\[A-Z][a-zA-Z\d]*)*'.
Line: 128

Element 'block', attribute 'class': 'bitExpert\ForceCustomerLogin\Block\Adminhtml\Manage\Create\Submit' is not a valid value of the atomic type 'blockClassType'.
Line: 128


Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'block', attribute 'class': [facet 'pattern'] The value 'bitExpert\ForceCustomerLogin\Block\Adminhtml\Manage\Create' is not accepted by the pattern '[A-Z][a-zA-Z\d]*(\\[A-Z][a-zA-Z\d]*)*'.
Line: 127

Element 'block', attribute 'class': 'bitExpert\ForceCustomerLogin\Block\Adminhtml\Manage\Create' is not a valid value of the atomic type 'blockClassType'.
Line: 127

Element 'block', attribute 'class': [facet 'pattern'] The value 'bitExpert\ForceCustomerLogin\Block\Adminhtml\Manage\Create\Submit' is not accepted by the pattern '[A-Z][a-zA-Z\d]*(\\[A-Z][a-zA-Z\d]*)*'.
Line: 128

Element 'block', attribute 'class': 'bitExpert\ForceCustomerLogin\Block\Adminhtml\Manage\Create\Submit' is not a valid value of the atomic type 'blockClassType'.
Line: 128

**Comment by websharp** [comment]
Hi @GalacticPlastic ,

you may want to try the newest release version [3.0.1](https://github.com/bitExpert/magento2-force-login/releases/tag/v3.0.1) by downloading manually or changing you composer.json file to apply to the newest version.

Best regards!

**Comment by shochdoerfer** [comment]
@GalacticPlastic in case you run into problems, open a new issue please. That will make it easier to manage for us. Thanks.
