### ISSUE TITLE
Magento 2.2 enterprise: naming convention error

### ISSUE THREAD

**Issue by AndrewAldayaABT** [bitExpert/magento2-force-login#93]
![screenshot from 2017-11-09 08-34-49](https://user-images.githubusercontent.com/33432616/32608336-0e537f5a-c52a-11e7-96b9-6c7198708aeb.png)

It seems in Magento 2.2 you cant start your module with a lowercase letter.

**Comment by AndrewAldayaABT** [comment]
added these to di.xml to fix issue

```
<preference for="BitExpert\ForceCustomerLogin\Block\Adminhtml\Manage\Create"
                type="bitExpert\ForceCustomerLogin\Block\Adminhtml\Manage\Create" />

    <preference for="BitExpert\ForceCustomerLogin\Block\Adminhtml\Manage\Create\Submit"
                type="bitExpert\ForceCustomerLogin\Block\Adminhtml\Manage\Create\Submit" />
```

**Comment by shochdoerfer** [comment]
perfect work-a-round ;)

**Comment by cmuench** [comment]
Haha

**Comment by rlieser** [comment]
aaaah, please, noooo!

**Comment by julienvb** [comment]
I added the code from @AndrewAldayaABT to di.xml but I still have the same error.
Does anybody know how to solve this issue? I am on M2.2. 

Ty!

**Comment by shochdoerfer** [comment]
@julienvb we will provide a fix soonish. Just a lot of other things happening that need our attention. Sorry.

**Comment by shochdoerfer** [comment]
@AndrewAldayaABT @julienvb could you please give the dev-master version a try? We just merged the PR in master. Would love to get your feedback before creating a new release. Thanks.

**Comment by julienvb** [comment]
Hi I actually implemented another solution so I can not give you feedback on your solution.
