### ISSUE TITLE
Component dependency is the only problem everything that prevents the install how can I fix?

### ISSUE THREAD

**Issue by JesseCastro1985** [bitExpert/magento2-force-login#96]
We found conflicting component dependencies. Hide detail

Command "update" failed: Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1
- bitexpert/magento2-force-customer-login 2.0.0 requires magento/module-customer ~100.0 -> satisfiable by magento/module-customer[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6, 100.1.0, 100.0.7, 100.0.8, 100.1.1, 100.0.9, 100.1.2, 100.1.3, 100.0.10, 100.1.4, 100.1.5, 100.0.11, 100.1.6, 100.0.12, 100.1.7, 100.1.8, 100.0.13, 100.0.14, 100.1.9].
- bitexpert/magento2-force-customer-login 2.0.0 requires magento/module-customer ~100.0 -> satisfiable by magento/module-customer[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6, 100.1.0, 100.0.7, 100.0.8, 100.1.1, 100.0.9, 100.1.2, 100.1.3, 100.0.10, 100.1.4, 100.1.5, 100.0.11, 100.1.6, 100.0.12, 100.1.7, 100.1.8, 100.0.13, 100.0.14, 100.1.9].
- Can only install one of: magento/module-customer[101.0.0, 100.0.2].
- Can only install one of: magento/module-customer[101.0.0, 100.0.3].
- Can only install one of: magento/module-customer[101.0.0, 100.0.4].
- Can only install one of: magento/module-customer[101.0.0, 100.0.5].
- Can only install one of: magento/module-customer[101.0.0, 100.0.6].
- Can only install one of: magento/module-customer[101.0.0, 100.1.0].
- Can only install one of: magento/module-customer[101.0.0, 100.0.7].
- Can only install one of: magento/module-customer[101.0.0, 100.0.8].
- Can only install one of: magento/module-customer[101.0.0, 100.1.1].
- Can only install one of: magento/module-customer[101.0.0, 100.0.9].
- Can only install one of: magento/module-customer[101.0.0, 100.1.2].
- Can only install one of: magento/module-customer[101.0.0, 100.1.3].
- Can only install one of: magento/module-customer[101.0.0, 100.0.10].
- Can only install one of: magento/module-customer[101.0.0, 100.1.4].
- Can only install one of: magento/module-customer[101.0.0, 100.1.5].
- Can only install one of: magento/module-customer[101.0.0, 100.0.11].
- Can only install one of: magento/module-customer[101.0.0, 100.1.6].
- Can only install one of: magento/module-customer[101.0.0, 100.0.12].
- Can only install one of: magento/module-customer[101.0.0, 100.1.7].
- Can only install one of: magento/module-customer[101.0.0, 100.1.8].
- Can only install one of: magento/module-customer[101.0.0, 100.0.13].
- Can only install one of: magento/module-customer[100.0.14, 101.0.0].
- Can only install one of: magento/module-customer[100.1.9, 101.0.0].
- magento/product-community-edition 2.2.0 requires magento/module-customer 101.0.0 -> satisfiable by magento/module-customer[101.0.0].
- Installation request for magento/product-community-edition 2.2.0 -> satisfiable by magento/product-community-edition[2.2.0].
- Installation request for bitexpert/magento2-force-customer-login 2.0.0 -> satisfiable by bitexpert/magento2-force-customer-login[2.0.0].

**Comment by websharp** [comment]
Hi @JesseCastro1985 ,

it seems you require a newer version of the force login module due to your Magento version. You may want to try this (download link at the bottom): https://github.com/bitExpert/magento2-force-login/releases/tag/v2.3.0

Best regards!

**Comment by shochdoerfer** [comment]
@JesseCastro1985 were you able to resolve the issue? If not, which Magento version are you using and which version of the force login module are you trying to install?

**Comment by shochdoerfer** [comment]
@JesseCastro1985 could you please check if the problem still exists in the latest 3.0.1 release?

**Comment by shochdoerfer** [comment]
Assuming this issue is resolved, I close this issue.
